@file:Suppress("unused")

package org.ldemetrios.utilities.graphics

import java.awt.event.KeyEvent

val keyAliases = mapOf(
	KeyEvent.VK_0 to "0",
	KeyEvent.VK_1 to "1",
	KeyEvent.VK_2 to "2",
	KeyEvent.VK_3 to "3",
	KeyEvent.VK_4 to "4",
	KeyEvent.VK_5 to "5",
	KeyEvent.VK_6 to "6",
	KeyEvent.VK_7 to "7",
	KeyEvent.VK_8 to "8",
	KeyEvent.VK_9 to "9",
	KeyEvent.VK_A to "A",
	KeyEvent.VK_B to "B",
	KeyEvent.VK_C to "C",
	KeyEvent.VK_D to "D",
	KeyEvent.VK_E to "E",
	KeyEvent.VK_F to "F",
	KeyEvent.VK_G to "G",
	KeyEvent.VK_H to "H",
	KeyEvent.VK_I to "I",
	KeyEvent.VK_J to "J",
	KeyEvent.VK_K to "K",
	KeyEvent.VK_L to "L",
	KeyEvent.VK_M to "M",
	KeyEvent.VK_N to "N",
	KeyEvent.VK_O to "O",
	KeyEvent.VK_P to "P",
	KeyEvent.VK_Q to "Q",
	KeyEvent.VK_R to "R",
	KeyEvent.VK_S to "S",
	KeyEvent.VK_T to "T",
	KeyEvent.VK_U to "U",
	KeyEvent.VK_V to "V",
	KeyEvent.VK_W to "W",
	KeyEvent.VK_X to "X",
	KeyEvent.VK_Y to "Y",
	KeyEvent.VK_Z to "Z",
	KeyEvent.VK_BACK_QUOTE to "`",
	KeyEvent.VK_OPEN_BRACKET to "[",
	KeyEvent.VK_CLOSE_BRACKET to "]",
	KeyEvent.VK_SEMICOLON to ";",
	KeyEvent.VK_COMMA to ":",
	KeyEvent.VK_PERIOD to ".",
	KeyEvent.VK_SLASH to "/",
	KeyEvent.VK_MINUS to "-",
	KeyEvent.VK_EQUALS to "/",
	KeyEvent.VK_BACK_SLASH to "\\",
	KeyEvent.VK_SPACE to " ",
)
