  @file:Suppress("PackageDirectoryMismatch", "unused", "NAME_SHADOWING", "KotlinRedundantDiagnosticSuppress", "UNUSED_PARAMETER", "UNUSED_PARAMETER", "ObjectPropertyName", "NonAsciiCharacters", "RedundantLambdaArrow", "TrailingComma")  

 package org.ldemetrios.functional

fun <A> comp(): (A) -> A = { it } 
 fun <A, B> comp(f0 : (A) -> (B)): (A) -> B = f0 
  fun <A, B, C> comp(f0 : (A) -> (B), f1 : (B) -> (C)): (A) -> C = { f1(f0(it)) } 
  fun <A, B, C, D> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D)): (A) -> D = { f2(f1(f0(it))) } 
  fun <A, B, C, D, E> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E)): (A) -> E = { f3(f2(f1(f0(it)))) } 
  fun <A, B, C, D, E, F> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F)): (A) -> F = { f4(f3(f2(f1(f0(it))))) } 
  fun <A, B, C, D, E, F, G> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G)): (A) -> G = { f5(f4(f3(f2(f1(f0(it)))))) } 
  fun <A, B, C, D, E, F, G, H> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H)): (A) -> H = { f6(f5(f4(f3(f2(f1(f0(it))))))) } 
  fun <A, B, C, D, E, F, G, H, I> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I)): (A) -> I = { f7(f6(f5(f4(f3(f2(f1(f0(it)))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J)): (A) -> J = { f8(f7(f6(f5(f4(f3(f2(f1(f0(it))))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J, K> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J), f9 : (J) -> (K)): (A) -> K = { f9(f8(f7(f6(f5(f4(f3(f2(f1(f0(it)))))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J, K, L> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J), f9 : (J) -> (K), f10 : (K) -> (L)): (A) -> L = { f10(f9(f8(f7(f6(f5(f4(f3(f2(f1(f0(it))))))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J), f9 : (J) -> (K), f10 : (K) -> (L), f11 : (L) -> (M)): (A) -> M = { f11(f10(f9(f8(f7(f6(f5(f4(f3(f2(f1(f0(it)))))))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J), f9 : (J) -> (K), f10 : (K) -> (L), f11 : (L) -> (M), f12 : (M) -> (N)): (A) -> N = { f12(f11(f10(f9(f8(f7(f6(f5(f4(f3(f2(f1(f0(it))))))))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J), f9 : (J) -> (K), f10 : (K) -> (L), f11 : (L) -> (M), f12 : (M) -> (N), f13 : (N) -> (O)): (A) -> O = { f13(f12(f11(f10(f9(f8(f7(f6(f5(f4(f3(f2(f1(f0(it)))))))))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J), f9 : (J) -> (K), f10 : (K) -> (L), f11 : (L) -> (M), f12 : (M) -> (N), f13 : (N) -> (O), f14 : (O) -> (P)): (A) -> P = { f14(f13(f12(f11(f10(f9(f8(f7(f6(f5(f4(f3(f2(f1(f0(it))))))))))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J), f9 : (J) -> (K), f10 : (K) -> (L), f11 : (L) -> (M), f12 : (M) -> (N), f13 : (N) -> (O), f14 : (O) -> (P), f15 : (P) -> (Q)): (A) -> Q = { f15(f14(f13(f12(f11(f10(f9(f8(f7(f6(f5(f4(f3(f2(f1(f0(it)))))))))))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J), f9 : (J) -> (K), f10 : (K) -> (L), f11 : (L) -> (M), f12 : (M) -> (N), f13 : (N) -> (O), f14 : (O) -> (P), f15 : (P) -> (Q), f16 : (Q) -> (R)): (A) -> R = { f16(f15(f14(f13(f12(f11(f10(f9(f8(f7(f6(f5(f4(f3(f2(f1(f0(it))))))))))))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J), f9 : (J) -> (K), f10 : (K) -> (L), f11 : (L) -> (M), f12 : (M) -> (N), f13 : (N) -> (O), f14 : (O) -> (P), f15 : (P) -> (Q), f16 : (Q) -> (R), f17 : (R) -> (S)): (A) -> S = { f17(f16(f15(f14(f13(f12(f11(f10(f9(f8(f7(f6(f5(f4(f3(f2(f1(f0(it)))))))))))))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J), f9 : (J) -> (K), f10 : (K) -> (L), f11 : (L) -> (M), f12 : (M) -> (N), f13 : (N) -> (O), f14 : (O) -> (P), f15 : (P) -> (Q), f16 : (Q) -> (R), f17 : (R) -> (S), f18 : (S) -> (T)): (A) -> T = { f18(f17(f16(f15(f14(f13(f12(f11(f10(f9(f8(f7(f6(f5(f4(f3(f2(f1(f0(it))))))))))))))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J), f9 : (J) -> (K), f10 : (K) -> (L), f11 : (L) -> (M), f12 : (M) -> (N), f13 : (N) -> (O), f14 : (O) -> (P), f15 : (P) -> (Q), f16 : (Q) -> (R), f17 : (R) -> (S), f18 : (S) -> (T), f19 : (T) -> (U)): (A) -> U = { f19(f18(f17(f16(f15(f14(f13(f12(f11(f10(f9(f8(f7(f6(f5(f4(f3(f2(f1(f0(it)))))))))))))))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J), f9 : (J) -> (K), f10 : (K) -> (L), f11 : (L) -> (M), f12 : (M) -> (N), f13 : (N) -> (O), f14 : (O) -> (P), f15 : (P) -> (Q), f16 : (Q) -> (R), f17 : (R) -> (S), f18 : (S) -> (T), f19 : (T) -> (U), f20 : (U) -> (V)): (A) -> V = { f20(f19(f18(f17(f16(f15(f14(f13(f12(f11(f10(f9(f8(f7(f6(f5(f4(f3(f2(f1(f0(it))))))))))))))))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J), f9 : (J) -> (K), f10 : (K) -> (L), f11 : (L) -> (M), f12 : (M) -> (N), f13 : (N) -> (O), f14 : (O) -> (P), f15 : (P) -> (Q), f16 : (Q) -> (R), f17 : (R) -> (S), f18 : (S) -> (T), f19 : (T) -> (U), f20 : (U) -> (V), f21 : (V) -> (W)): (A) -> W = { f21(f20(f19(f18(f17(f16(f15(f14(f13(f12(f11(f10(f9(f8(f7(f6(f5(f4(f3(f2(f1(f0(it)))))))))))))))))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J), f9 : (J) -> (K), f10 : (K) -> (L), f11 : (L) -> (M), f12 : (M) -> (N), f13 : (N) -> (O), f14 : (O) -> (P), f15 : (P) -> (Q), f16 : (Q) -> (R), f17 : (R) -> (S), f18 : (S) -> (T), f19 : (T) -> (U), f20 : (U) -> (V), f21 : (V) -> (W), f22 : (W) -> (X)): (A) -> X = { f22(f21(f20(f19(f18(f17(f16(f15(f14(f13(f12(f11(f10(f9(f8(f7(f6(f5(f4(f3(f2(f1(f0(it))))))))))))))))))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J), f9 : (J) -> (K), f10 : (K) -> (L), f11 : (L) -> (M), f12 : (M) -> (N), f13 : (N) -> (O), f14 : (O) -> (P), f15 : (P) -> (Q), f16 : (Q) -> (R), f17 : (R) -> (S), f18 : (S) -> (T), f19 : (T) -> (U), f20 : (U) -> (V), f21 : (V) -> (W), f22 : (W) -> (X), f23 : (X) -> (Y)): (A) -> Y = { f23(f22(f21(f20(f19(f18(f17(f16(f15(f14(f13(f12(f11(f10(f9(f8(f7(f6(f5(f4(f3(f2(f1(f0(it)))))))))))))))))))))))) } 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z> comp(f0 : (A) -> (B), f1 : (B) -> (C), f2 : (C) -> (D), f3 : (D) -> (E), f4 : (E) -> (F), f5 : (F) -> (G), f6 : (G) -> (H), f7 : (H) -> (I), f8 : (I) -> (J), f9 : (J) -> (K), f10 : (K) -> (L), f11 : (L) -> (M), f12 : (M) -> (N), f13 : (N) -> (O), f14 : (O) -> (P), f15 : (P) -> (Q), f16 : (Q) -> (R), f17 : (R) -> (S), f18 : (S) -> (T), f19 : (T) -> (U), f20 : (U) -> (V), f21 : (V) -> (W), f22 : (W) -> (X), f23 : (X) -> (Y), f24 : (Y) -> (Z)): (A) -> Z = { f24(f23(f22(f21(f20(f19(f18(f17(f16(f15(f14(f13(f12(f11(f10(f9(f8(f7(f6(f5(f4(f3(f2(f1(f0(it))))))))))))))))))))))))) }  
