  @file:Suppress("PackageDirectoryMismatch", "unused", "NAME_SHADOWING", "KotlinRedundantDiagnosticSuppress", "UNUSED_PARAMETER", "UNUSED_PARAMETER", "ObjectPropertyName", "NonAsciiCharacters", "RedundantLambdaArrow", "TrailingComma")  

 package org.ldemetrios.functional

fun <T> conj(list: List<T>): List<T> = list
  fun <T> conj(list: List<T>, a : T) : List<T> = list + listOf(a) 
  fun <T> conj(list: List<T>, a : T, b : T) : List<T> = list + listOf(a, b) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T) : List<T> = list + listOf(a, b, c) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T) : List<T> = list + listOf(a, b, c, d) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T) : List<T> = list + listOf(a, b, c, d, e) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T) : List<T> = list + listOf(a, b, c, d, e, f) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T) : List<T> = list + listOf(a, b, c, d, e, f, g) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i, j) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i, j, k) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i, j, k, l) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i, j, k, l, m) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i, j, k, l, m, n) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T, r : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T, r : T, s : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T, r : T, s : T, t : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T, r : T, s : T, t : T, u : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T, r : T, s : T, t : T, u : T, v : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T, r : T, s : T, t : T, u : T, v : T, w : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T, r : T, s : T, t : T, u : T, v : T, w : T, x : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x) 
  fun <T> conj(list: List<T>, a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T, r : T, s : T, t : T, u : T, v : T, w : T, x : T, y : T) : List<T> = list + listOf(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y)  
