  @file:Suppress("PackageDirectoryMismatch", "unused", "NAME_SHADOWING", "KotlinRedundantDiagnosticSuppress", "UNUSED_PARAMETER", "UNUSED_PARAMETER", "ObjectPropertyName", "NonAsciiCharacters", "RedundantLambdaArrow", "TrailingComma")  

 package org.ldemetrios.functional

 fun <T> equal( a : T, b : T ) : Boolean = a == b 
 fun <T> equal( a : T, b : T, c : T ) : Boolean = a == b && b == c 
 fun <T> equal( a : T, b : T, c : T, d : T ) : Boolean = a == b && b == c && c == d 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T ) : Boolean = a == b && b == c && c == d && d == e 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T ) : Boolean = a == b && b == c && c == d && d == e && e == f 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i && i == j 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i && i == j && j == k 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i && i == j && j == k && k == l 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i && i == j && j == k && k == l && l == m 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i && i == j && j == k && k == l && l == m && m == n 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i && i == j && j == k && k == l && l == m && m == n && n == o 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i && i == j && j == k && k == l && l == m && m == n && n == o && o == p 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i && i == j && j == k && k == l && l == m && m == n && n == o && o == p && p == q 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T, r : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i && i == j && j == k && k == l && l == m && m == n && n == o && o == p && p == q && q == r 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T, r : T, s : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i && i == j && j == k && k == l && l == m && m == n && n == o && o == p && p == q && q == r && r == s 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T, r : T, s : T, t : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i && i == j && j == k && k == l && l == m && m == n && n == o && o == p && p == q && q == r && r == s && s == t 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T, r : T, s : T, t : T, u : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i && i == j && j == k && k == l && l == m && m == n && n == o && o == p && p == q && q == r && r == s && s == t && t == u 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T, r : T, s : T, t : T, u : T, v : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i && i == j && j == k && k == l && l == m && m == n && n == o && o == p && p == q && q == r && r == s && s == t && t == u && u == v 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T, r : T, s : T, t : T, u : T, v : T, w : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i && i == j && j == k && k == l && l == m && m == n && n == o && o == p && p == q && q == r && r == s && s == t && t == u && u == v && v == w 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T, r : T, s : T, t : T, u : T, v : T, w : T, x : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i && i == j && j == k && k == l && l == m && m == n && n == o && o == p && p == q && q == r && r == s && s == t && t == u && u == v && v == w && w == x 
 fun <T> equal( a : T, b : T, c : T, d : T, e : T, f : T, g : T, h : T, i : T, j : T, k : T, l : T, m : T, n : T, o : T, p : T, q : T, r : T, s : T, t : T, u : T, v : T, w : T, x : T, y : T ) : Boolean = a == b && b == c && c == d && d == e && e == f && f == g && g == h && h == i && i == j && j == k && k == l && l == m && m == n && n == o && o == p && p == q && q == r && r == s && s == t && t == u && u == v && v == w && w == x && x == y   
