  @file:Suppress("PackageDirectoryMismatch", "unused", "NAME_SHADOWING", "KotlinRedundantDiagnosticSuppress", "UNUSED_PARAMETER", "UNUSED_PARAMETER", "ObjectPropertyName", "NonAsciiCharacters", "RedundantLambdaArrow", "TrailingComma")  

 package org.ldemetrios.functional

 typealias U = Unit

 val Ø = Unit

  operator fun <A, R> ((A) -> R).get( a : A ) : ( ) -> R = {  -> this(a) } 
 operator fun <A, R> ((A) -> R).get( a : U ) : (A,  ) -> R = { a,  -> this(a) }  

  operator fun <A, B, R> ((A, B) -> R).get( a : A, b : B ) : ( ) -> R = {  -> this(a, b) } 
 operator fun <A, B, R> ((A, B) -> R).get( a : U, b : B ) : (A,  ) -> R = { a,  -> this(a, b) } 
 operator fun <A, B, R> ((A, B) -> R).get( a : A, b : U ) : (B,  ) -> R = { b,  -> this(a, b) } 
 operator fun <A, B, R> ((A, B) -> R).get( a : U, b : U ) : (A, B,  ) -> R = { a, b,  -> this(a, b) }  

  operator fun <A, B, C, R> ((A, B, C) -> R).get( a : A, b : B, c : C ) : ( ) -> R = {  -> this(a, b, c) } 
 operator fun <A, B, C, R> ((A, B, C) -> R).get( a : U, b : B, c : C ) : (A,  ) -> R = { a,  -> this(a, b, c) } 
 operator fun <A, B, C, R> ((A, B, C) -> R).get( a : A, b : U, c : C ) : (B,  ) -> R = { b,  -> this(a, b, c) } 
 operator fun <A, B, C, R> ((A, B, C) -> R).get( a : U, b : U, c : C ) : (A, B,  ) -> R = { a, b,  -> this(a, b, c) } 
 operator fun <A, B, C, R> ((A, B, C) -> R).get( a : A, b : B, c : U ) : (C,  ) -> R = { c,  -> this(a, b, c) } 
 operator fun <A, B, C, R> ((A, B, C) -> R).get( a : U, b : B, c : U ) : (A, C,  ) -> R = { a, c,  -> this(a, b, c) } 
 operator fun <A, B, C, R> ((A, B, C) -> R).get( a : A, b : U, c : U ) : (B, C,  ) -> R = { b, c,  -> this(a, b, c) } 
 operator fun <A, B, C, R> ((A, B, C) -> R).get( a : U, b : U, c : U ) : (A, B, C,  ) -> R = { a, b, c,  -> this(a, b, c) }  

  operator fun <A, B, C, D, R> ((A, B, C, D) -> R).get( a : A, b : B, c : C, d : D ) : ( ) -> R = {  -> this(a, b, c, d) } 
 operator fun <A, B, C, D, R> ((A, B, C, D) -> R).get( a : U, b : B, c : C, d : D ) : (A,  ) -> R = { a,  -> this(a, b, c, d) } 
 operator fun <A, B, C, D, R> ((A, B, C, D) -> R).get( a : A, b : U, c : C, d : D ) : (B,  ) -> R = { b,  -> this(a, b, c, d) } 
 operator fun <A, B, C, D, R> ((A, B, C, D) -> R).get( a : U, b : U, c : C, d : D ) : (A, B,  ) -> R = { a, b,  -> this(a, b, c, d) } 
 operator fun <A, B, C, D, R> ((A, B, C, D) -> R).get( a : A, b : B, c : U, d : D ) : (C,  ) -> R = { c,  -> this(a, b, c, d) } 
 operator fun <A, B, C, D, R> ((A, B, C, D) -> R).get( a : U, b : B, c : U, d : D ) : (A, C,  ) -> R = { a, c,  -> this(a, b, c, d) } 
 operator fun <A, B, C, D, R> ((A, B, C, D) -> R).get( a : A, b : U, c : U, d : D ) : (B, C,  ) -> R = { b, c,  -> this(a, b, c, d) } 
 operator fun <A, B, C, D, R> ((A, B, C, D) -> R).get( a : U, b : U, c : U, d : D ) : (A, B, C,  ) -> R = { a, b, c,  -> this(a, b, c, d) } 
 operator fun <A, B, C, D, R> ((A, B, C, D) -> R).get( a : A, b : B, c : C, d : U ) : (D,  ) -> R = { d,  -> this(a, b, c, d) } 
 operator fun <A, B, C, D, R> ((A, B, C, D) -> R).get( a : U, b : B, c : C, d : U ) : (A, D,  ) -> R = { a, d,  -> this(a, b, c, d) } 
 operator fun <A, B, C, D, R> ((A, B, C, D) -> R).get( a : A, b : U, c : C, d : U ) : (B, D,  ) -> R = { b, d,  -> this(a, b, c, d) } 
 operator fun <A, B, C, D, R> ((A, B, C, D) -> R).get( a : U, b : U, c : C, d : U ) : (A, B, D,  ) -> R = { a, b, d,  -> this(a, b, c, d) } 
 operator fun <A, B, C, D, R> ((A, B, C, D) -> R).get( a : A, b : B, c : U, d : U ) : (C, D,  ) -> R = { c, d,  -> this(a, b, c, d) } 
 operator fun <A, B, C, D, R> ((A, B, C, D) -> R).get( a : U, b : B, c : U, d : U ) : (A, C, D,  ) -> R = { a, c, d,  -> this(a, b, c, d) } 
 operator fun <A, B, C, D, R> ((A, B, C, D) -> R).get( a : A, b : U, c : U, d : U ) : (B, C, D,  ) -> R = { b, c, d,  -> this(a, b, c, d) } 
 operator fun <A, B, C, D, R> ((A, B, C, D) -> R).get( a : U, b : U, c : U, d : U ) : (A, B, C, D,  ) -> R = { a, b, c, d,  -> this(a, b, c, d) }  

  operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : A, b : B, c : C, d : D, e : E ) : ( ) -> R = {  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : U, b : B, c : C, d : D, e : E ) : (A,  ) -> R = { a,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : A, b : U, c : C, d : D, e : E ) : (B,  ) -> R = { b,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : U, b : U, c : C, d : D, e : E ) : (A, B,  ) -> R = { a, b,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : A, b : B, c : U, d : D, e : E ) : (C,  ) -> R = { c,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : U, b : B, c : U, d : D, e : E ) : (A, C,  ) -> R = { a, c,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : A, b : U, c : U, d : D, e : E ) : (B, C,  ) -> R = { b, c,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : U, b : U, c : U, d : D, e : E ) : (A, B, C,  ) -> R = { a, b, c,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : A, b : B, c : C, d : U, e : E ) : (D,  ) -> R = { d,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : U, b : B, c : C, d : U, e : E ) : (A, D,  ) -> R = { a, d,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : A, b : U, c : C, d : U, e : E ) : (B, D,  ) -> R = { b, d,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : U, b : U, c : C, d : U, e : E ) : (A, B, D,  ) -> R = { a, b, d,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : A, b : B, c : U, d : U, e : E ) : (C, D,  ) -> R = { c, d,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : U, b : B, c : U, d : U, e : E ) : (A, C, D,  ) -> R = { a, c, d,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : A, b : U, c : U, d : U, e : E ) : (B, C, D,  ) -> R = { b, c, d,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : U, b : U, c : U, d : U, e : E ) : (A, B, C, D,  ) -> R = { a, b, c, d,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : A, b : B, c : C, d : D, e : U ) : (E,  ) -> R = { e,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : U, b : B, c : C, d : D, e : U ) : (A, E,  ) -> R = { a, e,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : A, b : U, c : C, d : D, e : U ) : (B, E,  ) -> R = { b, e,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : U, b : U, c : C, d : D, e : U ) : (A, B, E,  ) -> R = { a, b, e,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : A, b : B, c : U, d : D, e : U ) : (C, E,  ) -> R = { c, e,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : U, b : B, c : U, d : D, e : U ) : (A, C, E,  ) -> R = { a, c, e,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : A, b : U, c : U, d : D, e : U ) : (B, C, E,  ) -> R = { b, c, e,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : U, b : U, c : U, d : D, e : U ) : (A, B, C, E,  ) -> R = { a, b, c, e,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : A, b : B, c : C, d : U, e : U ) : (D, E,  ) -> R = { d, e,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : U, b : B, c : C, d : U, e : U ) : (A, D, E,  ) -> R = { a, d, e,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : A, b : U, c : C, d : U, e : U ) : (B, D, E,  ) -> R = { b, d, e,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : U, b : U, c : C, d : U, e : U ) : (A, B, D, E,  ) -> R = { a, b, d, e,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : A, b : B, c : U, d : U, e : U ) : (C, D, E,  ) -> R = { c, d, e,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : U, b : B, c : U, d : U, e : U ) : (A, C, D, E,  ) -> R = { a, c, d, e,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : A, b : U, c : U, d : U, e : U ) : (B, C, D, E,  ) -> R = { b, c, d, e,  -> this(a, b, c, d, e) } 
 operator fun <A, B, C, D, E, R> ((A, B, C, D, E) -> R).get( a : U, b : U, c : U, d : U, e : U ) : (A, B, C, D, E,  ) -> R = { a, b, c, d, e,  -> this(a, b, c, d, e) }  

  operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : B, c : C, d : D, e : E, f : F ) : ( ) -> R = {  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : B, c : C, d : D, e : E, f : F ) : (A,  ) -> R = { a,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : U, c : C, d : D, e : E, f : F ) : (B,  ) -> R = { b,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : U, c : C, d : D, e : E, f : F ) : (A, B,  ) -> R = { a, b,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : B, c : U, d : D, e : E, f : F ) : (C,  ) -> R = { c,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : B, c : U, d : D, e : E, f : F ) : (A, C,  ) -> R = { a, c,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : U, c : U, d : D, e : E, f : F ) : (B, C,  ) -> R = { b, c,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : U, c : U, d : D, e : E, f : F ) : (A, B, C,  ) -> R = { a, b, c,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : B, c : C, d : U, e : E, f : F ) : (D,  ) -> R = { d,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : B, c : C, d : U, e : E, f : F ) : (A, D,  ) -> R = { a, d,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : U, c : C, d : U, e : E, f : F ) : (B, D,  ) -> R = { b, d,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : U, c : C, d : U, e : E, f : F ) : (A, B, D,  ) -> R = { a, b, d,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : B, c : U, d : U, e : E, f : F ) : (C, D,  ) -> R = { c, d,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : B, c : U, d : U, e : E, f : F ) : (A, C, D,  ) -> R = { a, c, d,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : U, c : U, d : U, e : E, f : F ) : (B, C, D,  ) -> R = { b, c, d,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : U, c : U, d : U, e : E, f : F ) : (A, B, C, D,  ) -> R = { a, b, c, d,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : B, c : C, d : D, e : U, f : F ) : (E,  ) -> R = { e,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : B, c : C, d : D, e : U, f : F ) : (A, E,  ) -> R = { a, e,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : U, c : C, d : D, e : U, f : F ) : (B, E,  ) -> R = { b, e,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : U, c : C, d : D, e : U, f : F ) : (A, B, E,  ) -> R = { a, b, e,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : B, c : U, d : D, e : U, f : F ) : (C, E,  ) -> R = { c, e,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : B, c : U, d : D, e : U, f : F ) : (A, C, E,  ) -> R = { a, c, e,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : U, c : U, d : D, e : U, f : F ) : (B, C, E,  ) -> R = { b, c, e,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : U, c : U, d : D, e : U, f : F ) : (A, B, C, E,  ) -> R = { a, b, c, e,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : B, c : C, d : U, e : U, f : F ) : (D, E,  ) -> R = { d, e,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : B, c : C, d : U, e : U, f : F ) : (A, D, E,  ) -> R = { a, d, e,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : U, c : C, d : U, e : U, f : F ) : (B, D, E,  ) -> R = { b, d, e,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : U, c : C, d : U, e : U, f : F ) : (A, B, D, E,  ) -> R = { a, b, d, e,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : B, c : U, d : U, e : U, f : F ) : (C, D, E,  ) -> R = { c, d, e,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : B, c : U, d : U, e : U, f : F ) : (A, C, D, E,  ) -> R = { a, c, d, e,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : U, c : U, d : U, e : U, f : F ) : (B, C, D, E,  ) -> R = { b, c, d, e,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : U, c : U, d : U, e : U, f : F ) : (A, B, C, D, E,  ) -> R = { a, b, c, d, e,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : B, c : C, d : D, e : E, f : U ) : (F,  ) -> R = { f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : B, c : C, d : D, e : E, f : U ) : (A, F,  ) -> R = { a, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : U, c : C, d : D, e : E, f : U ) : (B, F,  ) -> R = { b, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : U, c : C, d : D, e : E, f : U ) : (A, B, F,  ) -> R = { a, b, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : B, c : U, d : D, e : E, f : U ) : (C, F,  ) -> R = { c, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : B, c : U, d : D, e : E, f : U ) : (A, C, F,  ) -> R = { a, c, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : U, c : U, d : D, e : E, f : U ) : (B, C, F,  ) -> R = { b, c, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : U, c : U, d : D, e : E, f : U ) : (A, B, C, F,  ) -> R = { a, b, c, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : B, c : C, d : U, e : E, f : U ) : (D, F,  ) -> R = { d, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : B, c : C, d : U, e : E, f : U ) : (A, D, F,  ) -> R = { a, d, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : U, c : C, d : U, e : E, f : U ) : (B, D, F,  ) -> R = { b, d, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : U, c : C, d : U, e : E, f : U ) : (A, B, D, F,  ) -> R = { a, b, d, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : B, c : U, d : U, e : E, f : U ) : (C, D, F,  ) -> R = { c, d, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : B, c : U, d : U, e : E, f : U ) : (A, C, D, F,  ) -> R = { a, c, d, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : U, c : U, d : U, e : E, f : U ) : (B, C, D, F,  ) -> R = { b, c, d, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : U, c : U, d : U, e : E, f : U ) : (A, B, C, D, F,  ) -> R = { a, b, c, d, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : B, c : C, d : D, e : U, f : U ) : (E, F,  ) -> R = { e, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : B, c : C, d : D, e : U, f : U ) : (A, E, F,  ) -> R = { a, e, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : U, c : C, d : D, e : U, f : U ) : (B, E, F,  ) -> R = { b, e, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : U, c : C, d : D, e : U, f : U ) : (A, B, E, F,  ) -> R = { a, b, e, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : B, c : U, d : D, e : U, f : U ) : (C, E, F,  ) -> R = { c, e, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : B, c : U, d : D, e : U, f : U ) : (A, C, E, F,  ) -> R = { a, c, e, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : U, c : U, d : D, e : U, f : U ) : (B, C, E, F,  ) -> R = { b, c, e, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : U, c : U, d : D, e : U, f : U ) : (A, B, C, E, F,  ) -> R = { a, b, c, e, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : B, c : C, d : U, e : U, f : U ) : (D, E, F,  ) -> R = { d, e, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : B, c : C, d : U, e : U, f : U ) : (A, D, E, F,  ) -> R = { a, d, e, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : U, c : C, d : U, e : U, f : U ) : (B, D, E, F,  ) -> R = { b, d, e, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : U, c : C, d : U, e : U, f : U ) : (A, B, D, E, F,  ) -> R = { a, b, d, e, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : B, c : U, d : U, e : U, f : U ) : (C, D, E, F,  ) -> R = { c, d, e, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : B, c : U, d : U, e : U, f : U ) : (A, C, D, E, F,  ) -> R = { a, c, d, e, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : A, b : U, c : U, d : U, e : U, f : U ) : (B, C, D, E, F,  ) -> R = { b, c, d, e, f,  -> this(a, b, c, d, e, f) } 
 operator fun <A, B, C, D, E, F, R> ((A, B, C, D, E, F) -> R).get( a : U, b : U, c : U, d : U, e : U, f : U ) : (A, B, C, D, E, F,  ) -> R = { a, b, c, d, e, f,  -> this(a, b, c, d, e, f) }  

  operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : C, d : D, e : E, f : F, g : G ) : ( ) -> R = {  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : C, d : D, e : E, f : F, g : G ) : (A,  ) -> R = { a,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : C, d : D, e : E, f : F, g : G ) : (B,  ) -> R = { b,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : C, d : D, e : E, f : F, g : G ) : (A, B,  ) -> R = { a, b,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : U, d : D, e : E, f : F, g : G ) : (C,  ) -> R = { c,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : U, d : D, e : E, f : F, g : G ) : (A, C,  ) -> R = { a, c,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : U, d : D, e : E, f : F, g : G ) : (B, C,  ) -> R = { b, c,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : U, d : D, e : E, f : F, g : G ) : (A, B, C,  ) -> R = { a, b, c,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : C, d : U, e : E, f : F, g : G ) : (D,  ) -> R = { d,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : C, d : U, e : E, f : F, g : G ) : (A, D,  ) -> R = { a, d,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : C, d : U, e : E, f : F, g : G ) : (B, D,  ) -> R = { b, d,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : C, d : U, e : E, f : F, g : G ) : (A, B, D,  ) -> R = { a, b, d,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : U, d : U, e : E, f : F, g : G ) : (C, D,  ) -> R = { c, d,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : U, d : U, e : E, f : F, g : G ) : (A, C, D,  ) -> R = { a, c, d,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : U, d : U, e : E, f : F, g : G ) : (B, C, D,  ) -> R = { b, c, d,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : U, d : U, e : E, f : F, g : G ) : (A, B, C, D,  ) -> R = { a, b, c, d,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : C, d : D, e : U, f : F, g : G ) : (E,  ) -> R = { e,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : C, d : D, e : U, f : F, g : G ) : (A, E,  ) -> R = { a, e,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : C, d : D, e : U, f : F, g : G ) : (B, E,  ) -> R = { b, e,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : C, d : D, e : U, f : F, g : G ) : (A, B, E,  ) -> R = { a, b, e,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : U, d : D, e : U, f : F, g : G ) : (C, E,  ) -> R = { c, e,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : U, d : D, e : U, f : F, g : G ) : (A, C, E,  ) -> R = { a, c, e,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : U, d : D, e : U, f : F, g : G ) : (B, C, E,  ) -> R = { b, c, e,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : U, d : D, e : U, f : F, g : G ) : (A, B, C, E,  ) -> R = { a, b, c, e,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : C, d : U, e : U, f : F, g : G ) : (D, E,  ) -> R = { d, e,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : C, d : U, e : U, f : F, g : G ) : (A, D, E,  ) -> R = { a, d, e,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : C, d : U, e : U, f : F, g : G ) : (B, D, E,  ) -> R = { b, d, e,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : C, d : U, e : U, f : F, g : G ) : (A, B, D, E,  ) -> R = { a, b, d, e,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : U, d : U, e : U, f : F, g : G ) : (C, D, E,  ) -> R = { c, d, e,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : U, d : U, e : U, f : F, g : G ) : (A, C, D, E,  ) -> R = { a, c, d, e,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : U, d : U, e : U, f : F, g : G ) : (B, C, D, E,  ) -> R = { b, c, d, e,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : U, d : U, e : U, f : F, g : G ) : (A, B, C, D, E,  ) -> R = { a, b, c, d, e,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : C, d : D, e : E, f : U, g : G ) : (F,  ) -> R = { f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : C, d : D, e : E, f : U, g : G ) : (A, F,  ) -> R = { a, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : C, d : D, e : E, f : U, g : G ) : (B, F,  ) -> R = { b, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : C, d : D, e : E, f : U, g : G ) : (A, B, F,  ) -> R = { a, b, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : U, d : D, e : E, f : U, g : G ) : (C, F,  ) -> R = { c, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : U, d : D, e : E, f : U, g : G ) : (A, C, F,  ) -> R = { a, c, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : U, d : D, e : E, f : U, g : G ) : (B, C, F,  ) -> R = { b, c, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : U, d : D, e : E, f : U, g : G ) : (A, B, C, F,  ) -> R = { a, b, c, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : C, d : U, e : E, f : U, g : G ) : (D, F,  ) -> R = { d, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : C, d : U, e : E, f : U, g : G ) : (A, D, F,  ) -> R = { a, d, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : C, d : U, e : E, f : U, g : G ) : (B, D, F,  ) -> R = { b, d, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : C, d : U, e : E, f : U, g : G ) : (A, B, D, F,  ) -> R = { a, b, d, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : U, d : U, e : E, f : U, g : G ) : (C, D, F,  ) -> R = { c, d, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : U, d : U, e : E, f : U, g : G ) : (A, C, D, F,  ) -> R = { a, c, d, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : U, d : U, e : E, f : U, g : G ) : (B, C, D, F,  ) -> R = { b, c, d, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : U, d : U, e : E, f : U, g : G ) : (A, B, C, D, F,  ) -> R = { a, b, c, d, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : C, d : D, e : U, f : U, g : G ) : (E, F,  ) -> R = { e, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : C, d : D, e : U, f : U, g : G ) : (A, E, F,  ) -> R = { a, e, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : C, d : D, e : U, f : U, g : G ) : (B, E, F,  ) -> R = { b, e, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : C, d : D, e : U, f : U, g : G ) : (A, B, E, F,  ) -> R = { a, b, e, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : U, d : D, e : U, f : U, g : G ) : (C, E, F,  ) -> R = { c, e, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : U, d : D, e : U, f : U, g : G ) : (A, C, E, F,  ) -> R = { a, c, e, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : U, d : D, e : U, f : U, g : G ) : (B, C, E, F,  ) -> R = { b, c, e, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : U, d : D, e : U, f : U, g : G ) : (A, B, C, E, F,  ) -> R = { a, b, c, e, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : C, d : U, e : U, f : U, g : G ) : (D, E, F,  ) -> R = { d, e, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : C, d : U, e : U, f : U, g : G ) : (A, D, E, F,  ) -> R = { a, d, e, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : C, d : U, e : U, f : U, g : G ) : (B, D, E, F,  ) -> R = { b, d, e, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : C, d : U, e : U, f : U, g : G ) : (A, B, D, E, F,  ) -> R = { a, b, d, e, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : U, d : U, e : U, f : U, g : G ) : (C, D, E, F,  ) -> R = { c, d, e, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : U, d : U, e : U, f : U, g : G ) : (A, C, D, E, F,  ) -> R = { a, c, d, e, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : U, d : U, e : U, f : U, g : G ) : (B, C, D, E, F,  ) -> R = { b, c, d, e, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : U, d : U, e : U, f : U, g : G ) : (A, B, C, D, E, F,  ) -> R = { a, b, c, d, e, f,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : C, d : D, e : E, f : F, g : U ) : (G,  ) -> R = { g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : C, d : D, e : E, f : F, g : U ) : (A, G,  ) -> R = { a, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : C, d : D, e : E, f : F, g : U ) : (B, G,  ) -> R = { b, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : C, d : D, e : E, f : F, g : U ) : (A, B, G,  ) -> R = { a, b, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : U, d : D, e : E, f : F, g : U ) : (C, G,  ) -> R = { c, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : U, d : D, e : E, f : F, g : U ) : (A, C, G,  ) -> R = { a, c, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : U, d : D, e : E, f : F, g : U ) : (B, C, G,  ) -> R = { b, c, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : U, d : D, e : E, f : F, g : U ) : (A, B, C, G,  ) -> R = { a, b, c, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : C, d : U, e : E, f : F, g : U ) : (D, G,  ) -> R = { d, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : C, d : U, e : E, f : F, g : U ) : (A, D, G,  ) -> R = { a, d, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : C, d : U, e : E, f : F, g : U ) : (B, D, G,  ) -> R = { b, d, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : C, d : U, e : E, f : F, g : U ) : (A, B, D, G,  ) -> R = { a, b, d, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : U, d : U, e : E, f : F, g : U ) : (C, D, G,  ) -> R = { c, d, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : U, d : U, e : E, f : F, g : U ) : (A, C, D, G,  ) -> R = { a, c, d, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : U, d : U, e : E, f : F, g : U ) : (B, C, D, G,  ) -> R = { b, c, d, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : U, d : U, e : E, f : F, g : U ) : (A, B, C, D, G,  ) -> R = { a, b, c, d, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : C, d : D, e : U, f : F, g : U ) : (E, G,  ) -> R = { e, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : C, d : D, e : U, f : F, g : U ) : (A, E, G,  ) -> R = { a, e, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : C, d : D, e : U, f : F, g : U ) : (B, E, G,  ) -> R = { b, e, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : C, d : D, e : U, f : F, g : U ) : (A, B, E, G,  ) -> R = { a, b, e, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : U, d : D, e : U, f : F, g : U ) : (C, E, G,  ) -> R = { c, e, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : U, d : D, e : U, f : F, g : U ) : (A, C, E, G,  ) -> R = { a, c, e, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : U, d : D, e : U, f : F, g : U ) : (B, C, E, G,  ) -> R = { b, c, e, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : U, d : D, e : U, f : F, g : U ) : (A, B, C, E, G,  ) -> R = { a, b, c, e, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : C, d : U, e : U, f : F, g : U ) : (D, E, G,  ) -> R = { d, e, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : C, d : U, e : U, f : F, g : U ) : (A, D, E, G,  ) -> R = { a, d, e, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : C, d : U, e : U, f : F, g : U ) : (B, D, E, G,  ) -> R = { b, d, e, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : C, d : U, e : U, f : F, g : U ) : (A, B, D, E, G,  ) -> R = { a, b, d, e, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : U, d : U, e : U, f : F, g : U ) : (C, D, E, G,  ) -> R = { c, d, e, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : U, d : U, e : U, f : F, g : U ) : (A, C, D, E, G,  ) -> R = { a, c, d, e, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : U, d : U, e : U, f : F, g : U ) : (B, C, D, E, G,  ) -> R = { b, c, d, e, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : U, d : U, e : U, f : F, g : U ) : (A, B, C, D, E, G,  ) -> R = { a, b, c, d, e, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : C, d : D, e : E, f : U, g : U ) : (F, G,  ) -> R = { f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : C, d : D, e : E, f : U, g : U ) : (A, F, G,  ) -> R = { a, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : C, d : D, e : E, f : U, g : U ) : (B, F, G,  ) -> R = { b, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : C, d : D, e : E, f : U, g : U ) : (A, B, F, G,  ) -> R = { a, b, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : U, d : D, e : E, f : U, g : U ) : (C, F, G,  ) -> R = { c, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : U, d : D, e : E, f : U, g : U ) : (A, C, F, G,  ) -> R = { a, c, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : U, d : D, e : E, f : U, g : U ) : (B, C, F, G,  ) -> R = { b, c, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : U, d : D, e : E, f : U, g : U ) : (A, B, C, F, G,  ) -> R = { a, b, c, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : C, d : U, e : E, f : U, g : U ) : (D, F, G,  ) -> R = { d, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : C, d : U, e : E, f : U, g : U ) : (A, D, F, G,  ) -> R = { a, d, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : C, d : U, e : E, f : U, g : U ) : (B, D, F, G,  ) -> R = { b, d, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : C, d : U, e : E, f : U, g : U ) : (A, B, D, F, G,  ) -> R = { a, b, d, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : U, d : U, e : E, f : U, g : U ) : (C, D, F, G,  ) -> R = { c, d, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : U, d : U, e : E, f : U, g : U ) : (A, C, D, F, G,  ) -> R = { a, c, d, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : U, d : U, e : E, f : U, g : U ) : (B, C, D, F, G,  ) -> R = { b, c, d, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : U, d : U, e : E, f : U, g : U ) : (A, B, C, D, F, G,  ) -> R = { a, b, c, d, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : C, d : D, e : U, f : U, g : U ) : (E, F, G,  ) -> R = { e, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : C, d : D, e : U, f : U, g : U ) : (A, E, F, G,  ) -> R = { a, e, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : C, d : D, e : U, f : U, g : U ) : (B, E, F, G,  ) -> R = { b, e, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : C, d : D, e : U, f : U, g : U ) : (A, B, E, F, G,  ) -> R = { a, b, e, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : U, d : D, e : U, f : U, g : U ) : (C, E, F, G,  ) -> R = { c, e, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : U, d : D, e : U, f : U, g : U ) : (A, C, E, F, G,  ) -> R = { a, c, e, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : U, d : D, e : U, f : U, g : U ) : (B, C, E, F, G,  ) -> R = { b, c, e, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : U, d : D, e : U, f : U, g : U ) : (A, B, C, E, F, G,  ) -> R = { a, b, c, e, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : C, d : U, e : U, f : U, g : U ) : (D, E, F, G,  ) -> R = { d, e, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : C, d : U, e : U, f : U, g : U ) : (A, D, E, F, G,  ) -> R = { a, d, e, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : C, d : U, e : U, f : U, g : U ) : (B, D, E, F, G,  ) -> R = { b, d, e, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : C, d : U, e : U, f : U, g : U ) : (A, B, D, E, F, G,  ) -> R = { a, b, d, e, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : B, c : U, d : U, e : U, f : U, g : U ) : (C, D, E, F, G,  ) -> R = { c, d, e, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : B, c : U, d : U, e : U, f : U, g : U ) : (A, C, D, E, F, G,  ) -> R = { a, c, d, e, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : A, b : U, c : U, d : U, e : U, f : U, g : U ) : (B, C, D, E, F, G,  ) -> R = { b, c, d, e, f, g,  -> this(a, b, c, d, e, f, g) } 
 operator fun <A, B, C, D, E, F, G, R> ((A, B, C, D, E, F, G) -> R).get( a : U, b : U, c : U, d : U, e : U, f : U, g : U ) : (A, B, C, D, E, F, G,  ) -> R = { a, b, c, d, e, f, g,  -> this(a, b, c, d, e, f, g) }   
