  @file:Suppress("PackageDirectoryMismatch", "unused", "NAME_SHADOWING", "KotlinRedundantDiagnosticSuppress", "UNUSED_PARAMETER", "UNUSED_PARAMETER", "ObjectPropertyName", "NonAsciiCharacters", "RedundantLambdaArrow", "TrailingComma")  

 package org.ldemetrios.functional

fun str() : String = ""
 fun <A> str(a : A) : String = a.toString()
 fun <A, B> str(a : A, b : B) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b); return sb.toString()
 }
 
  fun <A, B, C> str(a : A, b : B, c : C) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c); return sb.toString()
 }
 
  fun <A, B, C, D> str(a : A, b : B, c : C, d : D) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d); return sb.toString()
 }
 
  fun <A, B, C, D, E> str(a : A, b : B, c : C, d : D, e : E) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e); return sb.toString()
 }
 
  fun <A, B, C, D, E, F> str(a : A, b : B, c : C, d : D, e : E, f : F) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I, J> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I, j : J) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i)
 sb.append(j); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I, J, K> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I, j : J, k : K) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i)
 sb.append(j)
 sb.append(k); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I, J, K, L> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I, j : J, k : K, l : L) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i)
 sb.append(j)
 sb.append(k)
 sb.append(l); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I, j : J, k : K, l : L, m : M) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i)
 sb.append(j)
 sb.append(k)
 sb.append(l)
 sb.append(m); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I, j : J, k : K, l : L, m : M, n : N) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i)
 sb.append(j)
 sb.append(k)
 sb.append(l)
 sb.append(m)
 sb.append(n); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I, j : J, k : K, l : L, m : M, n : N, o : O) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i)
 sb.append(j)
 sb.append(k)
 sb.append(l)
 sb.append(m)
 sb.append(n)
 sb.append(o); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I, j : J, k : K, l : L, m : M, n : N, o : O, p : P) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i)
 sb.append(j)
 sb.append(k)
 sb.append(l)
 sb.append(m)
 sb.append(n)
 sb.append(o)
 sb.append(p); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I, j : J, k : K, l : L, m : M, n : N, o : O, p : P, q : Q) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i)
 sb.append(j)
 sb.append(k)
 sb.append(l)
 sb.append(m)
 sb.append(n)
 sb.append(o)
 sb.append(p)
 sb.append(q); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I, j : J, k : K, l : L, m : M, n : N, o : O, p : P, q : Q, r : R) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i)
 sb.append(j)
 sb.append(k)
 sb.append(l)
 sb.append(m)
 sb.append(n)
 sb.append(o)
 sb.append(p)
 sb.append(q)
 sb.append(r); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I, j : J, k : K, l : L, m : M, n : N, o : O, p : P, q : Q, r : R, s : S) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i)
 sb.append(j)
 sb.append(k)
 sb.append(l)
 sb.append(m)
 sb.append(n)
 sb.append(o)
 sb.append(p)
 sb.append(q)
 sb.append(r)
 sb.append(s); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I, j : J, k : K, l : L, m : M, n : N, o : O, p : P, q : Q, r : R, s : S, t : T) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i)
 sb.append(j)
 sb.append(k)
 sb.append(l)
 sb.append(m)
 sb.append(n)
 sb.append(o)
 sb.append(p)
 sb.append(q)
 sb.append(r)
 sb.append(s)
 sb.append(t); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I, j : J, k : K, l : L, m : M, n : N, o : O, p : P, q : Q, r : R, s : S, t : T, u : U) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i)
 sb.append(j)
 sb.append(k)
 sb.append(l)
 sb.append(m)
 sb.append(n)
 sb.append(o)
 sb.append(p)
 sb.append(q)
 sb.append(r)
 sb.append(s)
 sb.append(t)
 sb.append(u); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I, j : J, k : K, l : L, m : M, n : N, o : O, p : P, q : Q, r : R, s : S, t : T, u : U, v : V) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i)
 sb.append(j)
 sb.append(k)
 sb.append(l)
 sb.append(m)
 sb.append(n)
 sb.append(o)
 sb.append(p)
 sb.append(q)
 sb.append(r)
 sb.append(s)
 sb.append(t)
 sb.append(u)
 sb.append(v); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I, j : J, k : K, l : L, m : M, n : N, o : O, p : P, q : Q, r : R, s : S, t : T, u : U, v : V, w : W) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i)
 sb.append(j)
 sb.append(k)
 sb.append(l)
 sb.append(m)
 sb.append(n)
 sb.append(o)
 sb.append(p)
 sb.append(q)
 sb.append(r)
 sb.append(s)
 sb.append(t)
 sb.append(u)
 sb.append(v)
 sb.append(w); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I, j : J, k : K, l : L, m : M, n : N, o : O, p : P, q : Q, r : R, s : S, t : T, u : U, v : V, w : W, x : X) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i)
 sb.append(j)
 sb.append(k)
 sb.append(l)
 sb.append(m)
 sb.append(n)
 sb.append(o)
 sb.append(p)
 sb.append(q)
 sb.append(r)
 sb.append(s)
 sb.append(t)
 sb.append(u)
 sb.append(v)
 sb.append(w)
 sb.append(x); return sb.toString()
 }
 
  fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y> str(a : A, b : B, c : C, d : D, e : E, f : F, g : G, h : H, i : I, j : J, k : K, l : L, m : M, n : N, o : O, p : P, q : Q, r : R, s : S, t : T, u : U, v : V, w : W, x : X, y : Y) : String {
 val sb = StringBuilder()
 sb.append(a)
 sb.append(b)
 sb.append(c)
 sb.append(d)
 sb.append(e)
 sb.append(f)
 sb.append(g)
 sb.append(h)
 sb.append(i)
 sb.append(j)
 sb.append(k)
 sb.append(l)
 sb.append(m)
 sb.append(n)
 sb.append(o)
 sb.append(p)
 sb.append(q)
 sb.append(r)
 sb.append(s)
 sb.append(t)
 sb.append(u)
 sb.append(v)
 sb.append(w)
 sb.append(x)
 sb.append(y); return sb.toString()
 }
   
